const http = require("node:http");
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { Pool } = require("pg");

const PORT = Number(process.env.PORT || 4173);
const ROOT = __dirname;
const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) throw new Error("DATABASE_URL is required. Musei production uses PostgreSQL.");

const pool = new Pool({ connectionString: DATABASE_URL, max: Number(process.env.PGPOOL_MAX || 10) });
const q = (text, params = []) => pool.query(text, params);

const artifactsSeed = [
  ["Youth, Earth and Time", "K. Mullashev", "20th century", "Painting", "floor1", "Kazakh modern art", "A large expressive work from the A. Kasteev Museum category. It supports the pilot focus on Kazakh art, high-resolution viewing, and cultural storytelling.", "assets/museum/youth-earth-time.jpg", "https://commons.wikimedia.org/wiki/File:Youth_earth_and_time_by_K._Mullashev.jpg", "image-zoom"],
  ["The Legend of the World", "Isaac Itkind", "1957", "Sculpture", "floor2", "Sculpture and 3D studio", "Sculpture by Isaac Itkind. This item is useful for explaining how a real museum sculpture can become a scanned 3D model in the final system.", "assets/museum/itkind-legend-world.jpg", "https://commons.wikimedia.org/wiki/File:Isaac_Itkind_%E2%80%94_The_Legend_of_the_World_(1957).jpg", "future-3d"],
  ["Apples of Alma-Ata", "Evgeniy Sidorkin", "1980", "Graphics", "floor2", "Graphics and sketches", "Graphic work connected to Almaty identity. It fits the Lab 1 theme of cultural pride and digital access to heritage.", "assets/museum/apples-alma-ata.jpg", "https://commons.wikimedia.org/wiki/File:Evgeniy_Sidorkin_%E2%80%94_Apples_of_Alma-Ata_(1980).jpg", "image-zoom"],
  ["Gallery Room View", "A. Kasteev Museum interior", "2019", "Applied art", "floor1", "Virtual tour", "Interior view used as the tour background. It demonstrates the virtual route requirement before official 360-degree footage is available.", "assets/museum/kasteev-gallery-03.jpg", "https://commons.wikimedia.org/wiki/File:Rooms_of_State_Museum_of_Arts,_Almaty_03.jpg", "tour-panorama"]
];
const toursSeed = [
  ["3D tour: From Durer to Eifert", "BKDR / GMIRK public virtual exhibition", "https://bkdr.de/VRundgang/AlmatyKunstmuseum/", "https://www.gmirk.kz/ru/media-links/virtualnye-vystavki/233-3d-tur-po-vystavke-ot-dyurera-do-ejferta", "High-quality 360-degree exhibition route with artwork labels and room navigation.", "External exhibition route; exact official floor plan is not supplied in the public page.", "external-link", "Linked as an official public source. Copying, mirroring, or embedding the 360 assets requires permission from the museum/provider.", "The original viewer can be slow; Musei adds fast local login, profile, favorites, CMS, database proof, and guide functions around the source."],
  ["Artsteps Kasteev-style virtual exhibition", "Artsteps public viewer", "https://www.artsteps.com/view/6357caff66dd51fc4b199ac6?currentUser", "https://www.artsteps.com/", "Public WebGL exhibition space useful for comparing VR-style navigation and object information.", "External virtual gallery; not an official architectural floor layer.", "external-link", "Linked as an external public viewer. Assets and descriptions should not be copied into Musei without author permission or a clear license.", "Useful as a competitor/reference for virtual navigation, but not used as a copied local asset package."]
];

async function initDb() {
  await q(`
    CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_salt TEXT NOT NULL, password_hash TEXT NOT NULL, name TEXT NOT NULL, interest TEXT, language TEXT DEFAULT 'en', role TEXT NOT NULL DEFAULT 'visitor', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS profiles (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, city TEXT DEFAULT '', bio TEXT DEFAULT '', accessibility_mode TEXT DEFAULT 'standard', visit_goal TEXT DEFAULT '', updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS sessions (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, token TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS artifacts (id SERIAL PRIMARY KEY, title TEXT NOT NULL, artist TEXT, year TEXT, category TEXT NOT NULL, floor TEXT DEFAULT 'floor1', room TEXT DEFAULT '', description TEXT NOT NULL, image_url TEXT, source_url TEXT, model_type TEXT DEFAULT 'image-card', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS favorites (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, artifact_id INTEGER NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id, artifact_id));
    CREATE TABLE IF NOT EXISTS survey_responses (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, digital_use INTEGER NOT NULL, usefulness INTEGER NOT NULL, accessibility INTEGER NOT NULL, virtual_tours INTEGER NOT NULL, images_3d INTEGER NOT NULL, interactive_features INTEGER NOT NULL, future_intention INTEGER NOT NULL, readiness_score REAL NOT NULL, actual_class TEXT NOT NULL, predicted_class TEXT NOT NULL, result TEXT NOT NULL, notes TEXT DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS assistant_messages (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, question TEXT NOT NULL, answer TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS virtual_tours (id SERIAL PRIMARY KEY, title TEXT NOT NULL, provider TEXT NOT NULL, source_url TEXT NOT NULL, official_source_url TEXT DEFAULT '', coverage TEXT DEFAULT '', floor_scope TEXT DEFAULT '', integration_status TEXT NOT NULL DEFAULT 'external-link', rights_note TEXT NOT NULL, performance_note TEXT DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
  `);
  const artifactCount = Number((await q("SELECT COUNT(*)::int AS count FROM artifacts")).rows[0].count);
  if (!artifactCount) for (const item of artifactsSeed) await q("INSERT INTO artifacts (title, artist, year, category, floor, room, description, image_url, source_url, model_type) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)", item);
  const tourCount = Number((await q("SELECT COUNT(*)::int AS count FROM virtual_tours")).rows[0].count);
  if (!tourCount) for (const item of toursSeed) await q("INSERT INTO virtual_tours (title, provider, source_url, official_source_url, coverage, floor_scope, integration_status, rights_note, performance_note) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)", item);
  await seedAccount("visitor", process.env.MUSEI_DEMO_VISITOR_EMAIL || "demo@musei.local", process.env.MUSEI_DEMO_VISITOR_PASSWORD, "Demo Visitor", "Modern Kazakh art");
  await seedAccount("admin", process.env.MUSEI_DEMO_ADMIN_EMAIL || "admin@musei.local", process.env.MUSEI_DEMO_ADMIN_PASSWORD, "Musei Admin", "Database and project review");
}

function hashPassword(password, salt = crypto.randomBytes(16).toString("hex")) {
  return { salt, hash: crypto.pbkdf2Sync(password, salt, 120000, 32, "sha256").toString("hex") };
}
function timingSafeEqualHex(left, right) { const a = Buffer.from(left, "hex"), b = Buffer.from(right, "hex"); return a.length === b.length && crypto.timingSafeEqual(a, b); }
async function seedAccount(role, email, password, name, interest) {
  if (!password) return;
  const { salt, hash } = hashPassword(password);
  const existing = (await q("SELECT id FROM users WHERE email=$1", [email])).rows[0];
  let id = existing?.id;
  if (id) await q("UPDATE users SET password_salt=$1,password_hash=$2,name=$3,interest=$4,language='en',role=$5,updated_at=CURRENT_TIMESTAMP WHERE id=$6", [salt, hash, name, interest, role, id]);
  else id = (await q("INSERT INTO users (email,password_salt,password_hash,name,interest,language,role) VALUES ($1,$2,$3,$4,$5,'en',$6) RETURNING id", [email, salt, hash, name, interest, role])).rows[0].id;
  await q("INSERT INTO profiles (user_id, city, bio, visit_goal, updated_at) VALUES ($1,'Almaty',$2,$3,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET city=EXCLUDED.city,bio=EXCLUDED.bio,visit_goal=EXCLUDED.visit_goal,updated_at=CURRENT_TIMESTAMP", [id, role === "admin" ? "Admin account for showing PostgreSQL tables and implemented functions." : "Student demo visitor account.", role === "admin" ? "Review database tables and project infrastructure" : "Explore VR sources, collection, 3D demo, and survey classifier"]);
}
function publicUser(u) { return u && { id:u.id, email:u.email, name:u.name, interest:u.interest, language:u.language, role:u.role || "visitor", city:u.city || "", bio:u.bio || "", accessibilityMode:u.accessibility_mode || "standard", visitGoal:u.visit_goal || "" }; }
function tokenFrom(req) { const v = req.headers.authorization || ""; return v.startsWith("Bearer ") ? v.slice(7) : ""; }
async function currentUser(req) { const token = tokenFrom(req); if (!token) return null; return (await q(`SELECT users.*, profiles.city, profiles.bio, profiles.accessibility_mode, profiles.visit_goal FROM sessions JOIN users ON users.id=sessions.user_id LEFT JOIN profiles ON profiles.user_id=users.id WHERE sessions.token=$1`, [token])).rows[0] || null; }
async function requireUser(req, res) { const u = await currentUser(req); if (!u) json(res, 401, { error: "Please sign in first" }); return u; }
async function requireAdmin(req, res) { const u = await requireUser(req, res); if (!u) return null; if (u.role !== "admin") { json(res, 403, { error: "Admin account is required" }); return null; } return u; }
async function createSession(userId) { const token = crypto.randomBytes(32).toString("hex"); await q("INSERT INTO sessions (user_id, token) VALUES ($1,$2)", [userId, token]); return token; }
function n(value, fallback = 3) { const number = Number(value); return Number.isFinite(number) ? Math.min(5, Math.max(1, Math.round(number))) : fallback; }
function classify(input) { const digitalUse=n(input.digitalUse), usefulness=n(input.usefulness), accessibility=n(input.accessibility), virtualTours=n(input.virtualTours), images3d=n(input.images3d), interactive=n(input.interactive), futureIntention=n(input.futureIntention); const readiness=(digitalUse+usefulness+accessibility+virtualTours+images3d+interactive)/6; const predicted=readiness>=3.7?"Positive":"Negative", actual=futureIntention>=4?"Positive":"Negative"; const result=predicted==="Positive"&&actual==="Positive"?"TP":predicted==="Positive"?"FP":actual==="Positive"?"FN":"TN"; return {digitalUse,usefulness,accessibility,virtualTours,images3d,interactive,futureIntention,readiness,predicted,actual,result}; }
function answer(question) { const s=String(question||"").toLowerCase(); if (s.includes("database")||s.includes("postgres")||s.includes("password")) return "The production database is PostgreSQL. Passwords are stored only as salt plus PBKDF2 hash; plaintext passwords are never stored."; if (s.includes("tour")||s.includes("vr")||s.includes("360")) return "Musei links to official/public VR sources instead of copying 360 assets, then adds authentication, favorites, CMS, profile, survey, and database functions around them."; if (s.includes("role")||s.includes("admin")) return "Visitors use the museum functions; admins can additionally view database proof and manage artifact CMS records."; return "Musei Kasteev is a Kubernetes-deployed digital museum information system with PostgreSQL persistence, VR sources, collection, favorites, profile CRUD, admin CMS CRUD, survey classification, and a 3D model demo."; }
function json(res, status, payload) { res.writeHead(status, { "Content-Type":"application/json; charset=utf-8" }); res.end(JSON.stringify(payload)); }
function notFound(res) { json(res, 404, { error: "Not found" }); }
function body(req) { return new Promise((resolve,reject)=>{ let b=""; req.on("data", c=>{ b+=c; if (b.length>1_000_000) { reject(new Error("Request body is too large")); req.destroy(); }}); req.on("end",()=>{ try { resolve(b?JSON.parse(b):{}); } catch(e){ reject(e); }}); req.on("error",reject); }); }
async function snapshot() { return { users:(await q("SELECT id,email,role,password_salt,password_hash,name,interest,language,created_at,updated_at FROM users ORDER BY id DESC")).rows, profiles:(await q("SELECT * FROM profiles ORDER BY id DESC")).rows, artifacts:(await q("SELECT * FROM artifacts ORDER BY id DESC")).rows, virtual_tours:(await q("SELECT * FROM virtual_tours ORDER BY id DESC")).rows, favorites:(await q("SELECT * FROM favorites ORDER BY id DESC")).rows, survey_responses:(await q("SELECT * FROM survey_responses ORDER BY id DESC")).rows, assistant_messages:(await q("SELECT * FROM assistant_messages ORDER BY id DESC")).rows, sessions:(await q("SELECT id,user_id,substring(token from 1 for 12)||'...' AS token_preview,created_at FROM sessions ORDER BY id DESC")).rows }; }

async function api(req,res,pathname) {
  try {
    if (req.method === "GET" && pathname === "/api/healthz") return json(res,200,{status:"ok",app:"musei-kasteev",database:"postgresql"});
    if (req.method === "POST" && pathname === "/api/auth/register") { const b=await body(req), email=String(b.email||"").trim().toLowerCase(), password=String(b.password||""), name=String(b.name||"").trim(); if(!email||!password||!name) return json(res,400,{error:"Name, email, and password are required"}); if(password.length<6) return json(res,400,{error:"Use at least 6 password characters"}); const hp=hashPassword(password); const id=(await q("INSERT INTO users (email,password_salt,password_hash,name,interest) VALUES ($1,$2,$3,$4,$5) RETURNING id", [email,hp.salt,hp.hash,name,b.interest||"Modern Kazakh art"])).rows[0].id; await q("INSERT INTO profiles (user_id,visit_goal) VALUES ($1,$2)",[id,"Explore Kasteev digital route"]); return json(res,201,{token:await createSession(id)}); }
    if (req.method === "POST" && pathname === "/api/auth/login") { const b=await body(req), email=String(b.email||"").trim().toLowerCase(), password=String(b.password||""); const u=(await q("SELECT * FROM users WHERE email=$1",[email])).rows[0]; if(!u) return json(res,401,{error:"Invalid email or password"}); const hp=hashPassword(password,u.password_salt); if(!timingSafeEqualHex(hp.hash,u.password_hash)) return json(res,401,{error:"Invalid email or password"}); return json(res,200,{token:await createSession(u.id)}); }
    if (req.method === "GET" && pathname === "/api/me") { const u=await requireUser(req,res); if(!u) return; const fav=(await q("SELECT artifact_id FROM favorites WHERE user_id=$1",[u.id])).rows.map(r=>r.artifact_id); return json(res,200,{user:publicUser(u),favorites:fav}); }
    if (req.method === "PUT" && pathname === "/api/profile") { const u=await requireUser(req,res); if(!u) return; const b=await body(req); await q("UPDATE users SET name=$1,interest=$2,language=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$4",[b.name||u.name,b.interest||u.interest,b.language||u.language,u.id]); await q("INSERT INTO profiles (user_id,city,bio,updated_at) VALUES ($1,$2,$3,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET city=EXCLUDED.city,bio=EXCLUDED.bio,updated_at=CURRENT_TIMESTAMP",[u.id,b.city||"",b.bio||""]); return json(res,200,{ok:true}); }
    if (req.method === "DELETE" && pathname === "/api/account") { const u=await requireUser(req,res); if(!u) return; await q("DELETE FROM users WHERE id=$1",[u.id]); return json(res,200,{ok:true}); }
    if (req.method === "GET" && pathname === "/api/artifacts") return json(res,200,{artifacts:(await q("SELECT * FROM artifacts ORDER BY id DESC")).rows});
    if (req.method === "GET" && pathname === "/api/virtual-tours") return json(res,200,{tours:(await q("SELECT * FROM virtual_tours ORDER BY id")).rows});
    if (req.method === "POST" && pathname === "/api/artifacts") { if(!(await requireAdmin(req,res))) return; const b=await body(req); if(!b.title||!b.description) return json(res,400,{error:"Title and description are required"}); await q("INSERT INTO artifacts (title,artist,year,category,room,description,image_url,source_url) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)",[b.title,b.artist||"",b.year||"",b.category||"Painting",b.room||"",b.description,b.imageUrl||"assets/museum/kasteev-gallery-03.jpg",b.sourceUrl||"local demo entry"]); return json(res,201,{ok:true}); }
    const am=pathname.match(/^\/api\/artifacts\/(\d+)$/); if(am&&req.method==="PUT") { if(!(await requireAdmin(req,res))) return; const b=await body(req); await q("UPDATE artifacts SET title=$1,artist=$2,year=$3,category=$4,room=$5,description=$6,image_url=$7,updated_at=CURRENT_TIMESTAMP WHERE id=$8",[b.title,b.artist||"",b.year||"",b.category||"Painting",b.room||"",b.description,b.imageUrl||"assets/museum/kasteev-gallery-03.jpg",Number(am[1])]); return json(res,200,{ok:true}); } if(am&&req.method==="DELETE") { if(!(await requireAdmin(req,res))) return; await q("DELETE FROM artifacts WHERE id=$1",[Number(am[1])]); return json(res,200,{ok:true}); }
    if (req.method === "POST" && pathname === "/api/favorites") { const u=await requireUser(req,res); if(!u) return; const b=await body(req); await q("INSERT INTO favorites (user_id,artifact_id) VALUES ($1,$2) ON CONFLICT(user_id,artifact_id) DO NOTHING",[u.id,Number(b.artifactId)]); return json(res,201,{ok:true}); }
    const fm=pathname.match(/^\/api\/favorites\/(\d+)$/); if(fm&&req.method==="DELETE") { const u=await requireUser(req,res); if(!u) return; await q("DELETE FROM favorites WHERE user_id=$1 AND artifact_id=$2",[u.id,Number(fm[1])]); return json(res,200,{ok:true}); }
    if (req.method === "POST" && pathname === "/api/survey") { const u=await currentUser(req), b=await body(req), c=classify(b); const id=(await q("INSERT INTO survey_responses (user_id,digital_use,usefulness,accessibility,virtual_tours,images_3d,interactive_features,future_intention,readiness_score,actual_class,predicted_class,result,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id",[u?.id||null,c.digitalUse,c.usefulness,c.accessibility,c.virtualTours,c.images3d,c.interactive,c.futureIntention,c.readiness,c.actual,c.predicted,c.result,b.notes||""])).rows[0].id; return json(res,201,{result:{id,readiness_score:c.readiness,actual_class:c.actual,predicted_class:c.predicted,result:c.result}}); }
    if (req.method === "POST" && pathname === "/api/assistant") { const u=await currentUser(req), b=await body(req), question=String(b.question||"").trim(); if(!question) return json(res,400,{error:"Question is required"}); const a=answer(question); await q("INSERT INTO assistant_messages (user_id,question,answer) VALUES ($1,$2,$3)",[u?.id||null,question,a]); return json(res,201,{answer:a}); }
    if (req.method === "GET" && pathname === "/api/db/snapshot") { if(!(await requireAdmin(req,res))) return; return json(res,200,{database:"postgresql",tables:await snapshot()}); }
    notFound(res);
  } catch (e) { if(e.code==="23505") return json(res,409,{error:"This email is already registered"}); console.error(e); json(res,500,{error:e.message||"Server error"}); }
}
function serve(req,res,pathname) { const safe=pathname==="/"?"/index.html":pathname, file=path.normalize(path.join(ROOT,safe)); if(!file.startsWith(ROOT)) return notFound(res); fs.readFile(file,(err,data)=>{ if(err) return notFound(res); const ext=path.extname(file).toLowerCase(); const type={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png",".svg":"image/svg+xml"}[ext]||"application/octet-stream"; res.writeHead(200,{"Content-Type":type,"Cache-Control":[".html",".css",".js"].includes(ext)?"no-store":"public, max-age=3600"}); res.end(data); }); }
initDb().then(()=>http.createServer((req,res)=>{ const url=new URL(req.url,`http://${req.headers.host}`); if(url.pathname.startsWith("/api/")) return void api(req,res,url.pathname); serve(req,res,decodeURIComponent(url.pathname)); }).listen(PORT,"0.0.0.0",()=>console.log(`Musei Kasteev running on ${PORT} with PostgreSQL`))).catch(e=>{ console.error("Startup failed",e); process.exit(1); });
