apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: final-project
  namespace: argocd
spec:
  description: DevOps II final project GitOps project
  sourceRepos:
    - git://museum-git.gitops.svc.cluster.local/museum.git
    - https://github.com/yellowishcloud/museum.git
    - https://argoproj.github.io/argo-helm
    - https://prometheus-community.github.io/helm-charts
    - https://kubernetes.github.io/ingress-nginx
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://grafana.github.io/helm-charts
  destinations:
    - namespace: museum-prod
      server: https://kubernetes.default.svc
    - namespace: argo-rollouts
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: logging
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: museum-system
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: readonly-review
      description: Read-only project access for project review
      policies:
        - p, proj:final-project:readonly-review, applications, get, final-project/*, allow


