apiVersion: devops.aknie.kz/v1alpha1
kind: MuseumBackupPolicy
metadata:
  name: postgresql-daily
  namespace: museum-prod
  labels:
    app.kubernetes.io/name: musei-postgresql
    app.kubernetes.io/component: backup-policy
spec:
  pvcName: musei-postgresql-data
  schedule: daily-02:00
  retention: 7d
