apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap-nginx.yaml
  - storage.yaml
  - api-deployment.yaml
  - web-rollout.yaml
  - services.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - security.yaml
  - network-policies.yaml
  - backup-policy.yaml
