apiVersion: v1
kind: ServiceAccount
metadata:
  name: musei-api
  namespace: museum-prod
  labels:
    app.kubernetes.io/name: musei-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: musei-web
  namespace: museum-prod
  labels:
    app.kubernetes.io/name: musei-web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: musei-read-runtime
  namespace: museum-prod
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: musei-api-read-runtime
  namespace: museum-prod
subjects:
  - kind: ServiceAccount
    name: musei-api
    namespace: museum-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: musei-read-runtime
