apiVersion: v1
kind: ResourceQuota
metadata:
  name: museum-prod-quota
  namespace: museum-prod
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "3"
    limits.memory: 4Gi
    pods: "20"
    persistentvolumeclaims: "4"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: museum-prod-defaults
  namespace: museum-prod
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 150m
        memory: 192Mi
      max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: 10m
        memory: 32Mi
