apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musei-postgresql-data
  namespace: museum-prod
  labels:
    app.kubernetes.io/name: musei-postgresql
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
