apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/part-of: final-project
spec:
  project: final-project
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      values: |
        loki:
          enabled: true
          persistence:
            enabled: true
            size: 2Gi
        promtail:
          enabled: true
          config:
            clients:
              - url: http://logging-loki:3100/loki/api/v1/push
          readinessProbe: null
        grafana:
          enabled: false
        fluent-bit:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
