apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/final-project.yaml
  - applications/argo-rollouts.yaml
  - applications/monitoring.yaml
  - applications/custom-extension.yaml
  - applications/musei.yaml
